name: Deploy to cPanel
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.20.0"

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy via FTP
        run: |
          sudo apt-get install -y lftp
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; mirror -R --verbose --delete --parallel=4 ./dist /public_html; quit" ${{ secrets.FTP_SERVER }}
