name: Deploy to cPanel
on:
  push:
    branches:
      - prod
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: Build
        run: |
          npm install
          npm run build

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: d2c.shukran.store
          username: ftp_shukran@d2c.shukran.store
          password: n~W9;YR7LmxYTnRz
          port: 21
          local-dir: ./dist/
          server-dir: /home/d2cshukran/public_html/
          dangerous-clean-slate: false
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.vscode/**
            **/.env
